tabelltipp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView
from registration.forms import RegistrationFormUniqueEmail
from tabelltipp import settings

class MyRegistrationView(RegistrationView):
    form_class = RegistrationFormUniqueEmail

    def get_success_url(self, request, user):
        return '/'


urlpatterns = patterns('',
    url(r'^', include('tipp.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    (r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.ADMIN_ENABLED:
    urlpatterns += patterns('',
        url(r'^admin/', include(admin.site.urls)),
        )

tipp/urls.py
from django.conf.urls import patterns, url
from tipp import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^tabell/(?P<tabell_slug>[\w\-]+)/$', views.tabell, name='tabell'),
                       url(r'^ligaer/$', views.ligaer, name='ligaer'),
                       url(r'^blimediliga/(?P<liga_slug>[\w\-]+)/$', views.blimediliga, name='blimediliga'),
                       url(r'^blimediligaform/$', views.blimediligaform, name='blimediligaform'),
                       url(r'^regnpoeng/$', views.regnpoeng, name='regnpoeng'),
                       url(r'^opprettliga/$', views.opprett_liga, name='opprettliga'),
                       url(r'^liga/(?P<liganavn_slug>[\w\-]+)/$', views.liga, name='liga'),
                       url(r'^se-tipp/(?P<liga_slug>[\w\-]+)/(?P<user_slug>[\w\-]+)/$', views.se_tipp, name='se_tipp'),
                       )

tipp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from urllib.request import urlopen
from datetime import datetime
from pytz import timezone


class Tabell(models.Model):
    navn = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(unique=True)
    url = models.URLField(null=True)
    updated = models.DateTimeField(default=datetime.now(), null=True)

    def __str__(self):
        return self.navn

    def reloaddata(self):
        error_occured = False
        timeinorge = datetime.now(timezone("Europe/Oslo")).hour
        try:
            assert(13 <= self.updated.astimezone(timezone("Europe/Oslo")).hour < 22 or 13 <= timeinorge < 22)
            assert(False)
            f = urlopen(self.url).read().decode('unicode-escape').replace('Hodd','Hødd').replace('Strommen', 'Strømmen').replace('Baerum', 'Bærum').replace('Honefoss','Hønefoss').replace("Valerenga", 'Vålerenga').replace("Mjondalen", "Mjøndalen").replace("Lillestrom", "Lillestrøm").replace("Tromso", "Tromsø").replace("Bodo","Bodø").replace("Strom", "Strøm")
        except:
            return False

        for lag in Lag.objects.filter(tabell=self):
            try:
#               stats = f.split("Hjemmetabell")[1].split(lag.navn.split()[0])[1].split("</tr>")[0].replace('\t','').replace('<td>','').replace('</td>','').splitlines()[1:9]
                stats = f.split(lag.navn.split()[0])[2].split("</tr>")[0]
                stats = [l.split('>')[-1] for l in stats.split('<')]
                stats = [int(x) for x in stats if x[-1:].isdigit()][-13:-5]

                lag.kamper_spilt = stats[0]
                lag.seire = stats[1]
                lag.uavgjort = stats[2]
                lag.tap = stats[3]
                lag.scoretemaal = stats[4]
                lag.maal = '%d - %d'%(stats[4], stats[5])
                lag.maalforskjell = stats[6]
                lag.poeng = stats[7] if lag.navn != "Lillestrøm" else stats[7]-1
                lag.save()
            except:
                error_occured = True

        self.updated = datetime.now(timezone("Europe/Oslo"))
        self.save()

        if error_occured:
            return False
        else:
            return True


class Lag(models.Model):
    navn = models.CharField(max_length=128, unique=True)
    poeng = models.IntegerField(default=0)
    kamper_spilt = models.IntegerField(default=0)
    seire = models.IntegerField(default=0, null=True)
    uavgjort = models.IntegerField(default=0, null=True)
    tap = models.IntegerField(default=0, null=True)
    maalforskjell = models.IntegerField(default=0)
    scoretemaal = models.IntegerField(default=0)
    maal = models.CharField(default='0 - 0', max_length=12, null=True)
    tabell = models.ForeignKey(Tabell)
    sorteringsnavn = models.CharField(max_length=128, null=True)

    def save(self, *args, **kwargs):
        self.sorteringsnavn = self.navn.lower().replace('aa', 'å')
        super().save(*args, **kwargs)

    def __str__(self):
        return self.navn

    class Meta:
        ordering = ["-poeng", "-maalforskjell", "-scoretemaal", "kamper_spilt", "sorteringsnavn"]
        verbose_name_plural = 'lag'


class PoengRegel(models.Model):
    navn = models.CharField(max_length=128, unique=True)
    kortnavn = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.navn


class Liga(models.Model):
    navn = models.CharField(max_length=128, unique=True)
    public = models.BooleanField(default=True)
    tabell = models.ForeignKey(Tabell)
    poengregel = models.ForeignKey(PoengRegel)
    deltakere = models.ManyToManyField(User, through='Tabelltipp')
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.navn)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.navn


class Tabelltipp(models.Model):
    user = models.ForeignKey(User, null=True)
    liga = models.ForeignKey(Liga, null=True)
    plassertlag = models.ManyToManyField(Lag, through='TippetPlassering')
    poeng = models.IntegerField(default=0)

    def getpoeng(self):
        poengid = self.liga.poengregel.kortnavn
        poengvektor = [tipp.getpoengfortipp() for tipp in TippetPlassering.objects.filter(tabelltipp=self)]

        if "kvadrat" in poengid:
            poengvektor = [poeng**2 for poeng in poengvektor]
            self.poeng = 1000-sum(poengvektor)

        else:
            self.poeng = 100-sum(poengvektor)

        self.save()

    class Meta:
        ordering = ["-poeng"]


class TippetPlassering(models.Model):
    lag = models.ForeignKey(Lag, null=True)
    tabelltipp = models.ForeignKey(Tabelltipp, null=True)
    tippet_plassering = models.IntegerField()

    def getpoengfortipp(self):
        poengid = self.tabelltipp.liga.poengregel.kortnavn
        lagitabell = Lag.objects.filter(tabell=self.lag.tabell)
        if "plassering" in poengid:
            plassitabell = [l.id for l in lagitabell].index(self.lag.id)+1
            return abs(plassitabell-int(self.tippet_plassering))

        elif "poeng" in poengid:
            return abs(self.lag.poeng-lagitabell[int(self.tippet_plassering)-1].poeng)

    class Meta:
        ordering = ["tippet_plassering"]

tipp/forms.py
from django.forms import ModelForm
from tipp.models import Liga

class OpprettLiga(ModelForm):
    class Meta:
        model = Liga
        fields = ('navn', 'tabell', 'poengregel')

from django import forms

class ExampleForm(forms.Form):
    username = forms.CharField(max_length=30, label=u'Username')
    email = forms.EmailField(label=u'Email address')

tipp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
from tipp.models import Lag, Liga, Tabell, Tabelltipp, TippetPlassering, PoengRegel
from tipp.forms import OpprettLiga
import simplejson as json
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'tipp/index.html', {})

    user = request.user
    mine_ligaer = user.liga_set.all()
    for liga in mine_ligaer:
        liga.minplass = 1+Tabelltipp.objects.filter(liga=liga, poeng__gt=Tabelltipp.objects.get(user=user, liga=liga).poeng).count()

    return render(request, 'tipp/index.html', {'liga': mine_ligaer})


def tabell(request, tabell_slug):
    tabell = Tabell.objects.get(slug=tabell_slug)
    tabell.reloaddata()
    lag = Lag.objects.filter(tabell=tabell)
    tabell.lag = lag
    context_dict = {'tabell': tabell}
    return render(request, 'tipp/tabell.html', context_dict)

@login_required
def ligaer(request):
    liga_list = Liga.objects.filter(public=True)
    for l in liga_list:
        l.antall = User.objects.filter(tabelltipp__liga=l).count()

    context_dict = {'ligaer': liga_list}

    return render(request, 'tipp/ligaer.html', context_dict)

@login_required
def liga(request, liganavn_slug):
    context_dict = {}
    try:
        liga = Liga.objects.get(slug=liganavn_slug)
        liga.tabell.reloaddata()
        context_dict['liganavn'] = liga.navn

        tabelltipp = Tabelltipp.objects.filter(liga=liga)
        for tipp in tabelltipp:
            tipp.getpoeng()

        tabelltipp = Tabelltipp.objects.filter(liga=liga)
        for d in tabelltipp:
            d.sinplass = 1+Tabelltipp.objects.filter(liga=liga, poeng__gt=Tabelltipp.objects.get(user=d.user, liga=liga).poeng).count()
        context_dict['tabelltipp'] = tabelltipp
        context_dict['liga'] = liga

        deltakere = liga.deltakere.all()
        if request.user in deltakere:
            context_dict['userinliga'] = True

    except Liga.DoesNotExist:
        pass

    return render(request, 'tipp/liga.html', context_dict)


@login_required
def opprett_liga(request):
    if request.method == "POST":
        form = OpprettLiga(request.POST)
        if form.is_valid():
            slug = slugify(request.POST['navn'])
            if Liga.objects.filter(slug=slug) or slug == '':
                pass
            else:
                try:
                    ligaobject = form.save(commit=True)
                    return blimediliga(request, ligaobject.slug)

                except:
                    pass
    else:
        form = OpprettLiga()

    tabeller = Tabell.objects.all()
    poengregler = PoengRegel.objects.all()
    context_dict = {"form": form, "tabeller": tabeller, "poengregler": poengregler}

    return render(request, 'tipp/opprettliga.html', context_dict)


@login_required
def blimediliga(request, liga_slug):
    liga = Liga.objects.get(slug=liga_slug)
    lag = Lag.objects.filter(tabell=liga.tabell)
    context_dict = {'lag': lag, 'liga': liga}
    return render(request, 'tipp/blimediliga.html', context_dict)


@login_required
def blimediligaform(request):
    if request.method == 'GET':
        ligaid = request.GET['ligaid']
        ordning = [int(i) for i in str(request.GET['ordning']).split('_')]
        user = request.user
        if Tabelltipp.objects.filter(user=user, liga_id=ligaid).count() > 0:
            return
        tabelltipp = Tabelltipp()
        tabelltipp.user = user
        tabelltipp.liga = Liga.objects.get(id=ligaid)
        tabelltipp.save()
        for tippetplassering, lagid in enumerate(ordning):
            tipp = TippetPlassering()
            tipp.lag = Lag.objects.get(id=lagid)
            tipp.tabelltipp = tabelltipp
            tipp.tippet_plassering = tippetplassering+1
            tipp.save()
    messages.add_message(request, messages.INFO, "admin")
    return


@login_required
def se_tipp(request, liga_slug, user_slug):
    user = request.user
    brukeren = User.objects.get(username=user_slug).username
    ligaen = Liga.objects.get(slug=liga_slug)
    if user not in ligaen.deltakere.all():
        messages.add_message(request, messages.INFO, brukeren)
        return redirect('liga',ligaen.slug)
    tabelltipp = Tabelltipp.objects.filter(user__username=user_slug, liga__slug=liga_slug).first()
    plassertlag=TippetPlassering.objects.filter(tabelltipp=tabelltipp).all()
    return render(request, 'tipp/se_tipp.html', {'tabelltipp': tabelltipp, 'plassertlag': plassertlag, 'bruker': brukeren, 'liga': ligaen})


@login_required
def regnpoeng(request):
    lagid = request.GET["lagid"]
    tabelltippid = request.GET["tabelltippid"]

    lag = Lag.objects.get(id=lagid)
    lagitabell = Lag.objects.filter(tabell=lag.tabell).all()
    plassitabell = [l.id for l in lagitabell].index(lag.id)+1
    poeng = lag.poeng
    tabelltipp = Tabelltipp.objects.get(id=tabelltippid)
    tipp = TippetPlassering.objects.get(tabelltipp=tabelltipp, lag=lag)
    minuspoeng = tipp.getpoengfortipp()

    results = {"lag": str(lag.navn), "plass": str(plassitabell), "poeng": str(poeng), "minuspoeng": str(minuspoeng)}
    return HttpResponse(json.dumps(results))

templates/tipp/blimediliga.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Tipp tabellen for å bli med i ligaen {{ liga.navn }}{% endblock %}

{% block body_block %}
<h2 class="sub-header">Tipp tabell</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr class="success">
<!--                  <th>#</th>
-->
                  <th>Lag</th>
                </tr>
              </thead>
              <tbody id="sortable">
              {% for l in lag %}
                <tr id='{{ l.id }}' class="tabell">
<!--                  <td>{{ forloop.counter }}</td>
-->
                  <td>{{ l.navn }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
<button class="btn btn-lg btn-primary" id="blimed" data-ligaid="{{ liga.id }}" data-redirecturl="{% url 'liga' liga.slug %}">Tipp!</button>
{% endblock %}

templates/tipp/dropdownmenu.html
{% for tabell in tabeller %}
<li><a href="{% url 'tabell' tabell.slug %}">{{ tabell.navn }}</a></li>
{% endfor %}

templates/tipp/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Hjem{% endblock %}
{% block body_block %}

{% if user.is_authenticated %}
{% if liga %}
    <h2 class="sub-header">Mine ligaer</h2>

          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr class="success">
                  <th>Liga</th>
                  <th>Tabell</th>
                  <th>Plass</th>
                </tr>
              </thead>
              <tbody>
              {% for l in liga %}
                <tr class="clickable-row" data-href={% url 'liga' l.slug %}>
                  <td>{{ l.navn }}</td>
                  <td>{{ l.tabell.navn }}</td>
                  <td>{{ l.minplass }}/{{ l.deltakere.all|length }}</td>
                  
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>

{% else %}
<h2 class="sub-header">Du er ikke medlem i noen liga enda!</h2>
{% endif %}

<div class="col-md-6">
<p><a class="btn btn-md btn-success btn-block" href="{% url 'opprettliga' %}" role="button">Opprett ny liga</a></p>
</div>
<div class="col-md-6">
<p><a class="btn btn-md btn-success btn-block" href="{% url 'ligaer' %}" role="button">Finn en liga</a></p>
</div>

{% endif %}


{% endblock %}

templates/tipp/liga.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ liganavn }}{% endblock %}
{% block body_block %}

{% if liga %}
    <h2 class="sub-header">Stillingen i {{ liganavn }}</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr class="success">
                  <th>#</th>
                  <th>Bruker</th>
                  <th>Poeng</th>
                </tr>
              </thead>
              <tbody>
              {% for d in tabelltipp %}
                <tr class="clickable-row" {% if userinliga %}{% else %}data-inliga="false"{% endif %} data-href={% url 'se_tipp' liga.slug d.user.username %}>
                  <td>{{ d.sinplass }}</td>
                  <td>{{ d.user.username }}</td>
                  <td>{{ d.poeng }}</td>
                  
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
{% if not userinliga %}
<p><a class="btn btn-md btn-success btn-block" href="{% url 'blimediliga' liga.slug %}" role="button">Bli med</a></p>
{% endif %}
{% for message in  messages %}
{% if message.message == "admin" %}
<script>
 $("#freeow").freeow("Velkommen!", "Du er nå med i ligaen {{ liga.navn }}!", { classes: ["smokey", "notice"]});
</script>
{% else %}
<div class="alert alert-warning" role="alert">
  <strong>NB!</strong> Bli med i ligaen for å se tabelltippet til {{ message }}.
</div>
{% endif %}
{% endfor %}
<div>
    <p class="text-muted"> I denne ligaen tippes det om {{ liga.tabell }}, og {{liga.poengregel|lower }} blir brukt som poengregel.</p>
</div>
{% else %}
    <h2 class="sub-header">Denne ligaen finnes ikke!</h2>
{% endif %}
{% endblock %}

templates/tipp/ligaer.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Offentlige ligaer{% endblock %}
{% block body_block %}

{% if ligaer %}
    <h2 class="sub-header">Tilgjengelige ligaer</h2>

          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr class="success">
                  <th>Liga</th>
                  <th>Tabell</th>
                  <th>Deltakere</th>
                </tr>
              </thead>
              <tbody>
              {% for l in ligaer %}
                <tr class="clickable-row" data-href={% url 'liga' l.slug %}>
                  <td>{{ l.navn }}</td>
                  <td>{{ l.tabell.navn }}</td>
                  <td>{{ l.antall }}</td>

                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>


<div class="col-md-6">
<p><a class="btn btn-md btn-success btn-block" href="{% url 'opprettliga' %}" role="button">Opprett ny liga</a></p>
</div>
{% else %}
<h2 class="sub-header">Det finnes ingen ligaer enda!</h2>
<div class="col-md-6">
<p><a class="btn btn-md btn-success btn-block" href="{% url 'opprettliga' %}" role="button">Opprett ny liga</a></p>
</div>
{% endif %}

{% endblock %}

templates/tipp/opprettliga.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{% endblock %}
{% block body_block %}

<form role="form"  method="post" action=".">
{% csrf_token %}
<div class="new-login-left">
<h2 class="form-signin-heading">Opprett liga her!</h2>

<div class="form-group" >
 <p class="required"> <label for="id_navn">Navn på liga:</label>
     <input class="form-control" id="id_navn" maxlength="30" name="navn" type="text"  placeholder="Velg liganavn"/></p>
</div>
 <div class="form-group selectpicker">
    <p class="required"><label for="tabell">Tabell:</label>
        <select class="form-control" id="tabell" name="tabell" type="selectpicker" placeholder="Velg tabell" /></p>
{% for tabell in tabeller %}
<option value="{{ tabell.id }}">{{ tabell }}</option>
{% endfor %}
</select>
 </div>
<div class="form-group selectpicker">
    <p class="required"><label for="poengregel">Poengregel:</label>
        <select class="form-control" id="poengregel" name="poengregel" type="selectpicker" placeholder="-----" /></p>
{% for poengregel in poengregler %}
<option value="{{ poengregel.id }}">{{ poengregel }}</option>
{% endfor %}
</select>
</div>

<button type="submit" class="btn btn-lg btn-primary btn-block">Opprett</button>
</div>
</form>
{% endblock %}

templates/tipp/se_tipp.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Tippet tabell{% endblock %}

{% block body_block %}
<h2 class="sub-header">Tippet tabell av {{ bruker }} i {{ liga.navn }}.</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr class="success">
                  <th>#</th>
                  <th>Lag</th>
                </tr>
              </thead>
              <tbody>
              {% for l in plassertlag %}
                <tr class="table-row" data-lagid="{{ l.lag.id }}" data-tabelltippid="{{ tabelltipp.id }}">
                  <td>{{ forloop.counter }}</td>
                  <td>{{ l.lag.navn }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
<div>
    <p class="text-muted">{{liga.poengregel }} blir brukt som poengregel.</p>
</div>

{% endblock %}

templates/tipp/signup.html
{% if signup %}
<div class="jumbotron">
  <h1>Tipp Tabelltipp!</h1>
  <p class="lead">Har du peiling på fotball, og har en forkjærlighet for gambling? Da er du kommet på rett plass! Vær med på tabelltippekonkurransen!</p>
  <p><a class="btn btn-lg btn-success" href="{% url 'registration_register' %}" role="button">Bli med idag</a></p>
</div>
{% endif %}

templates/tipp/tabell.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Tabell{% endblock %}

{% block body_block %}
<h2 class="sub-header">{{ tabell.navn }}</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr class='success'>
                  <th>#</th>
                  <th>Lag</th>
                  <th>S</th> 
                  <th>Mål</th> 
                  <th>Poeng</th>
                </tr>
              </thead>
              <tbody>
              {% for l in tabell.lag %}
                <tr class="tabell">
                  <td>{{ forloop.counter }}</td>
                  <td>{{ l.navn }}</td>
                  <td>{{ l.kamper_spilt }}</td> 
                  <td>{{ l.maal }}</td> 
                  <td>{{ l.poeng }}</td> 
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
{% endblock %}

templates/tipp/tipptabell.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Tipp tabell{% endblock %}

{% block body_block %}
<h2 class="sub-header">Tipp tabell</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Lag</th>
                </tr>
              </thead>
              <tbody id="sortable">
              {% for l in lag %}
                <tr id='{{ l.id }}'>
                  <td>{{ l.navn }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
  <button id="knapp" data-lagid="{{ l.id }}">Tipp!</button>

{% endblock %}